# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImClient

  target 'ImClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ImClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImClient-tvOS

  target 'ImClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

platform :ios, '8.0'

target '<your_project_name>' do
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
end
