export const CLOSE_MUNE = 'CLOSE_MUNE';
export const CHANGE_LOGGIN_STATE = 'CHANGE_LOGGIN_STATE_MUNE';
export const CHANGE_KEY_HEIGHT = 'CHANGE_KEY_HEIGHT';
export const GET_ROSTER = 'GET_ROSTER';
export const CHANGE_FETCH_STATE = 'CHANGE_FETCH_STATE';
export const CAHNGE_CHAT = 'CAHNGE_CHAT';
export const CAHNGE_GROUP = 'CAHNGE_GROUP'; // 群聊
export const SEND_GROUP_CHAT_INFO = 'SEND_GROUP_CHAT_INFO'; // 发送群聊信息成功
export const CHANGE_CHAT_ROOMS = 'CHANGE_CHAT_ROOMS'; // 用户个人聊天, 非群组
export const SAVE_USERID = 'SAVE_USERID'; // 登录成功保存用户id
export const SWITCH_CHAT_TOP = 'SWITCH_CHAT_TOP'; // 切换聊天顶置功能
export const SET_GROUP_NAME = 'SET_GROUP_NAME'; // 设置群聊群名称
export const SET_GROUP_USERNAME = 'SET_GROUP_USERNAME' // 设置群聊用户在群众的昵称
export const ON_TEXT_MESSAGE = "ON_TEXT_MESSAGE" // 监听用户收到的文本消息